---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

quickpsy is an R library to fits psychometric functions for several conditions. 

## Install

First, you need to download and install [R](http://cran.rstudio.com) (we also recommend [Rstudio](http://www.rstudio.com/)).

Then, you need to install the package boot, DEoptim, devtools, dplyr, ggplot2 and 
tidyr.
For example, to install devtools

```R
install.packages('devtools')
```

and then to install quickpsy from github 

```R
library(devtools)
devtools::install_github('danilinares/quickpsy', build_vignettes = T)
```

The vignettes, which have extra tutorials, take a while to be built. If you don't want to build them use `build_vignettes = F` in the command above).

## Example

```R
library(boot)
library(DEoptim)
library(dplyr)
library(ggplot2)
library(tidyr)

library(MPDiR) # contains the Vernier data
data(Vernier) # ?Venier for the reference
fit <- quickpsy(Vernier, Phaseshift, NumUpward, N,
                grouping = .(Direction, WaveForm, TempFreq))
plotcurves(fit)
plotpara(fit)
plotthresholds(fit)
```

## Help and tutorials

For specific functions
```R
?plotcurves
```
You can find further guidande in the vignettes (if you build them)

```R
browseVignettes('quickpsy')
```

Software|Language|Multiple fits|Guess and lapses|Bootstrap
-----|:-----|:----|:----|:----|:----
modelfree|R|No|No|No
quickpsy|R|Yes|Yes|Yes
psyphy|R|No|Yes|No
psignifit|python|No|Yes|Yes
palamedes|MATLAB|Yes|Yes|Yes

