###############################################
library(dplyr)
library(ggplot2)
library(boot)
library(tidyr)

data <- quickreadfiles('inst/extdata/linareslopezmolinerjohnston2007/',
                   obs = c('dl','ss','at'), exp = c('exp1'))

### no groups
fit <- quickpsy(data, FASE, RESP, B = 10)
plotcurves(fit)
plotcurves(fit, averages = T, curves = F, thresholds = F, ci = F)
plotpara(fit)
plotpara(fit, geom = 'point')
plotthresholds(fit)
plotthresholds(fit, geom = 'point')

### 1 group
fit <- quickpsy(data, FASE, RESP, random = .(EXC_F), B = 10)
plotcurves(fit)
plotpara(fit)
plotpara(fit, x = EXC_F)
plotpara(fit, color = EXC_F)
plotpara(fit, geom = 'point')
plotpara(fit, x = EXC_F, geom = 'point')
plotpara(fit, color = EXC_F, geom = 'point')
plotthresholds(fit)
plotthresholds(fit, x = EXC_F)
plotthresholds(fit, color = EXC_F)
plotthresholds(fit, geom = 'point')
plotthresholds(fit, x = EXC_F, geom = 'point')
plotthresholds(fit, color = EXC_F, geom = 'point')

### 2 groups
fit <- quickpsy(data, FASE, RESP, random = .(EXC_F, obs), B = 10)
plotcurves(fit)
plotcurves(fit, ypanel = EXC_F)
plotcurves(fit, xpanel = EXC_F)
plotcurves(fit, ypanel = obs)
plotcurves(fit, xpanel = obs)
plotpara(fit)
plotpara(fit, x = EXC_F)
plotpara(fit, x = obs)
plotpara(fit, color = EXC_F)
plotpara(fit, color = obs)
plotpara(fit, geom  = 'point')
plotpara(fit, x = EXC_F, geom = 'point')
plotpara(fit, x = obs, geom = 'point')
plotpara(fit, color = EXC_F, geom = 'point')
plotpara(fit, color = obs, geom = 'point')

### 3 groups
fit <- quickpsy(data, FASE, RESP, random = .(EXC_F, obs, INTERVAL), B = 10)
plotcurves(fit)
plotcurves(fit, ypanel = EXC_F)
plotcurves(fit, xpanel = EXC_F)
plotcurves(fit, color = EXC_F)
plotcurves(fit, ypanel = obs)
plotcurves(fit, xpanel = obs)
plotcurves(fit, color = obs)
plotcurves(fit, ypanel = INTERVAL)
plotcurves(fit, xpanel = INTERVAL)
plotcurves(fit, color = INTERVAL)

plotcurves(fit, xpanel = obs, color = EXC_F)
plotcurves(fit, xpanel = obs, color = INTERVAL)
plotcurves(fit, xpanel = EXC_F, color = obs)
plotcurves(fit, xpanel = EXC_F, color = INTERVAL)
plotcurves(fit, xpanel = INTERVAL, color = obs)
plotcurves(fit, xpanel = INTERVAL, color = EXC_F)

plotcurves(fit, xpanel = obs, ypanel = EXC_F)
plotcurves(fit, xpanel = obs, ypanel = INTERVAL)
plotcurves(fit, xpanel = EXC_F, ypanel = obs)
plotcurves(fit, xpanel = EXC_F, ypanel = INTERVAL)
plotcurves(fit, xpanel = INTERVAL, ypanel = obs)
plotcurves(fit, xpanel = INTERVAL, ypanel = EXC_F)

plotcurves(fit, xpanel = INTERVAL, ypanel = EXC_F, color = obs)
plotcurves(fit, xpanel = INTERVAL, ypanel = obs, color = EXC_F)
plotcurves(fit, xpanel = EXC_F, ypanel = INTERVAL, color = obs)
plotcurves(fit, xpanel = EXC_F, ypanel = obs, color = INTERVAL)
plotcurves(fit, xpanel = obs, ypanel = INTERVAL, color = EXC_F)
plotcurves(fit, xpanel = obs, ypanel = EXC_F, color = INTERVAL)

plotpara(fit)
plotpara(fit, x = EXC_F)
plotpara(fit, x = obs)
plotpara(fit, x = INTERVAL)
plotpara(fit, color = EXC_F)
plotpara(fit, color = obs)
plotpara(fit, color = INTERVAL)
plotpara(fit, ypanel = EXC_F)
plotpara(fit, ypanel = obs)
plotpara(fit, ypanel = INTERVAL)
plotpara(fit, xpanel = EXC_F)
plotpara(fit, xpanel = obs)
plotpara(fit, xpanel = INTERVAL)

plotpara(fit, x = EXC_F, color = obs)
plotpara(fit, x = EXC_F, color = INTERVAL)
plotpara(fit, x = obs, color = EXC_F)
plotpara(fit, x = obs, color = INTERVAL)
plotpara(fit, x = INTERVAL, color = EXC_F)
plotpara(fit, x = INTERVAL, color = obs)

plotpara(fit, x = EXC_F, color = obs, ypanel = INTERVAL)
plotpara(fit, x = EXC_F, color = INTERVAL, ypanel = obs)
plotpara(fit, x = obs, color = EXC_F, ypanel = INTERVAL)
plotpara(fit, x = obs, color = INTERVAL, ypanel = EXC_F)
plotpara(fit, x = INTERVAL, color = EXC_F, ypanel = obs)
plotpara(fit, x = INTERVAL, color = obs, ypanel = EXC_F)


plotpara(fit, geom = 'point')
plotpara(fit, x = EXC_F, geom = 'point')
plotpara(fit, x = obs, geom = 'point')
plotpara(fit, x = INTERVAL, geom = 'point')
plotpara(fit, color = EXC_F, geom = 'point')
plotpara(fit, color = obs, geom = 'point')
plotpara(fit, color = INTERVAL, geom = 'point')
plotpara(fit, ypanel = EXC_F, geom = 'point')
plotpara(fit, ypanel = obs, geom = 'point')
plotpara(fit, ypanel = INTERVAL, geom = 'point')
plotpara(fit, xpanel = EXC_F, geom = 'point')
plotpara(fit, xpanel = obs, geom = 'point')
plotpara(fit, xpanel = INTERVAL, geom = 'point')

plotpara(fit, x = EXC_F, color = obs, geom = 'point')
plotpara(fit, x = EXC_F, color = INTERVAL, geom = 'point')
plotpara(fit, x = obs, color = EXC_F, geom = 'point')
plotpara(fit, x = obs, color = INTERVAL, geom = 'point')
plotpara(fit, x = INTERVAL, color = EXC_F, geom = 'point')
plotpara(fit, x = INTERVAL, color = obs, geom = 'point')

plotpara(fit, x = EXC_F, color = obs, ypanel = INTERVAL, geom = 'point')
plotpara(fit, x = EXC_F, color = INTERVAL, ypanel = obs, geom = 'point')
plotpara(fit, x = obs, color = EXC_F, ypanel = INTERVAL, geom = 'point')
plotpara(fit, x = obs, color = INTERVAL, ypanel = EXC_F, geom = 'point')
plotpara(fit, x = INTERVAL, color = EXC_F, ypanel = obs, geom = 'point')
plotpara(fit, x = INTERVAL, color = obs, ypanel = EXC_F, geom = 'point')



plotthresholds(fit)
plotthresholds(fit, x = EXC_F)
plotthresholds(fit, x = obs)
plotthresholds(fit, x = INTERVAL)
plotthresholds(fit, color = EXC_F)
plotthresholds(fit, color = obs)
plotthresholds(fit, color = INTERVAL)
plotthresholds(fit, panel = EXC_F)
plotthresholds(fit, panel = obs)
plotthresholds(fit, panel = INTERVAL)
plotthresholds(fit, ypanel = EXC_F)
plotthresholds(fit, ypanel = obs)
plotthresholds(fit, ypanel = INTERVAL)
plotthresholds(fit, xpanel = EXC_F)
plotthresholds(fit, xpanel = obs)
plotthresholds(fit, xpanel = INTERVAL)

plotthresholds(fit, x = EXC_F, color = obs)
plotthresholds(fit, x = EXC_F, color = INTERVAL)
plotthresholds(fit, x = obs, color = EXC_F)
plotthresholds(fit, x = obs, color = INTERVAL)
plotthresholds(fit, x = INTERVAL, color = EXC_F)
plotthresholds(fit, x = INTERVAL, color = obs)

plotthresholds(fit, x = EXC_F, color = obs, ypanel = INTERVAL)
plotthresholds(fit, x = EXC_F, color = INTERVAL, ypanel = obs)
plotthresholds(fit, x = obs, color = EXC_F, ypanel = INTERVAL)
plotthresholds(fit, x = obs, color = INTERVAL, ypanel = EXC_F)
plotthresholds(fit, x = INTERVAL, color = EXC_F, ypanel = obs)
plotthresholds(fit, x = INTERVAL, color = obs, ypanel = EXC_F)



plotthresholds(fit, geom = 'point')
plotthresholds(fit, x = EXC_F, geom = 'point')
plotthresholds(fit, x = obs, geom = 'point')
plotthresholds(fit, x = INTERVAL, geom = 'point')
plotthresholds(fit, color = EXC_F, geom= 'point')
plotthresholds(fit, color = obs, geom= 'point')
plotthresholds(fit, color = INTERVAL, geom= 'point')
plotthresholds(fit, panel = EXC_F, geom= 'point')
plotthresholds(fit, panel = obs, geom= 'point')
plotthresholds(fit, panel = INTERVAL, geom= 'point')
plotthresholds(fit, ypanel = EXC_F, geom= 'point')
plotthresholds(fit, ypanel = obs, geom= 'point')
plotthresholds(fit, ypanel = INTERVAL, geom= 'point')
plotthresholds(fit, xpanel = EXC_F, geom= 'point')
plotthresholds(fit, xpanel = obs, geom= 'point')
plotthresholds(fit, xpanel = INTERVAL, geom= 'point')

plotthresholds(fit, x = EXC_F, color = obs, geom= 'point')
plotthresholds(fit, x = EXC_F, color = INTERVAL, geom= 'point')
plotthresholds(fit, x = obs, color = EXC_F, geom= 'point')
plotthresholds(fit, x = obs, color = INTERVAL, geom= 'point')
plotthresholds(fit, x = INTERVAL, color = EXC_F, geom= 'point')
plotthresholds(fit, x = INTERVAL, color = obs, geom= 'point')

plotthresholds(fit, x = EXC_F, color = obs, ypanel = INTERVAL, geom= 'point')
plotthresholds(fit, x = EXC_F, color = INTERVAL, ypanel = obs, geom= 'point')
plotthresholds(fit, x = obs, color = EXC_F, ypanel = INTERVAL, geom= 'point')
plotthresholds(fit, x = obs, color = INTERVAL, ypanel = EXC_F, geom= 'point')
plotthresholds(fit, x = INTERVAL, color = EXC_F, ypanel = obs, geom= 'point')
plotthresholds(fit, x = INTERVAL, color = obs, ypanel = EXC_F, geom= 'point')

### NSE
fit <- quickpsy_(data, 'FASE', 'RESP', random = c('EXC_F', 'obs', 'INTERVAL'), B = 10)
plotcurves(fit)
plotcurves(fit, ypanel = EXC_F)
plotcurves_(fit, ypanel = 'EXC_F')
plotthresholds(fit, x = EXC_F, geom = 'point')
plotthresholds_(fit, x = 'EXC_F', geom = 'point')


### different shapes
fit_cum_normal_fun <- quickpsy(data, FASE, RESP, fun = cum_normal_fun)
fit_logistic_fun <- quickpsy(data, FASE, RESP, fun = logistic_fun)
fit_weibull_fun <- quickpsy(data, FASE, RESP, fun = weibull_fun)

cum <- fit_cum_normal_fun$curves %>% mutate(fun = 'cumulative normal')
logi <- fit_logistic_fun$curves %>% mutate(fun = 'logistic function')
wei <- fit_weibull_fun$curves %>% mutate(fun = 'weibull')

curv <- rbind(cum, logi, wei)

ggplot()+
  geom_line(data = curv, aes(x = x, y = y, color = fun)) +
  geom_point(data = fit_cum_normal_fun$averages, aes(x = FASE, y = y ))

### lapses and guesses
fit <- quickpsy(data, FASE, RESP, guess = .25)
plotcurves(fit)
fit <- quickpsy(data, FASE, RESP, lapses = .25)
plotcurves(fit)
fit <- quickpsy(data, FASE, RESP, guess = .25, lapses = .25)
plotcurves(fit)
fit <- quickpsy(data, FASE, RESP, guess = T)
plotcurves(fit)
fit <- quickpsy(data, FASE, RESP, lapses = T)
plotcurves(fit)
fit <- quickpsy(data, FASE, RESP, guess = T, lapses = T, B = 100)
plotcurves(fit)

### it doesn't work
fit <- quickpsy(data, FASE, RESP, random = .(EXC_F, obs, INTERVAL), guess = T)
plotcurves(fit)

